### ISSUE TITLE
Documentation references execute/1 which doesn't seem to exist

### ISSUE THREAD

**Issue by cjbottaro** [infinitered/elasticsearch-elixir#11]

**Comment by steffkes** [comment]
I guess you're referring to this doc-block in [elasticsearch.ex](https://github.com/infinitered/elasticsearch-elixir/blob/ce904e5dea959a5caefe2cde15669bba43ac3fa6/lib/elasticsearch.ex#L225-L226)?

```
Posts data or queries to a given Elasticsearch path. If you want to execute
an `Elasticsearch.Query`, see `execute/1` instead.
```
since there is no previous commit to this part, i'd say that this reflects @danielberkompas initial thoughts about this library could/would be built .. but it wasn't actually implemented for some reasons and we could remove it
