### ISSUE TITLE
Elasticsearch.StreamingStore behaviour or something alike

### ISSUE THREAD

**Issue by imranismail** [infinitered/elasticsearch-elixir#31]
Reason being we could utilize `Repo.stream` with `Repo.transaction` with timeout of infinity.

LIMIT + OFFSET is linear when getting the last 100 in a 1 million row table. I'll have to go through the first 99900. Using a cursor or a stream with a timeout of infinity can help in this case.

Right now I avoid having long queries (waiting for the offset to reach 99900) by doing something like this:

```
        User
        |> select([:name, :email, :phone, :id])
        |> Repo.stream()
        |> Stream.drop(offset)
        |> Enum.take(limit)
```

But streaming to the end in one shot would be much much preferred.

**Comment by imranismail** [comment]
This can also play well when data is ingested from a GenStage producer.

**Comment by danielberkompas** [comment]
See `Elasticsearch.DataStream`. It uses an `Elasticsearch.Store` to generate a stream. It doesn't use `Repo.transaction`, because we don't want `elasticsearch-elixir` to rely on Ecto in any way.

The best way forward would probably be to add an optional `stream/0` callback to the `Elasticsearch.Store` behaviour, which will then be used by `Elasticsearch.DataStream` if you define it.

Then, you could create your `Repo`-based stream in your store and have the `DataStream` module just delegate to it.

**Comment by danielberkompas** [comment]
@imranismail I have a PR open to do this: #36. Do you have any feedback?

**Comment by cdunn** [comment]
@danielberkompas @imranismail The switch to streams impacts the ability to preload relationships
`warning: passing a query with preloads to Repo.stream/2 leads to erratic behaviour and will raise in future Ecto versions`
https://github.com/elixir-ecto/ecto/issues/2424
...i'm still looking at how to handle appropriately but just thought I'd mention

**Comment by danielberkompas** [comment]
I think the solution might be to use a database cursor instead of `Repo.stream`. I did this [in Cloak](https://github.com/danielberkompas/cloak/blob/master/lib/cloak/migrator/cursor_stream.ex) and it seems to work well.
